### PR TITLE
Hotfix gulpfile assertion error

### PR DESCRIPTION
**Pull request by Megalomaniak**
Fixes the following error encountered during `npm run build`:

```
assert.js:340
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (d:\xampp-7.3.2\htdocs\newforum\themes\Bootstrap\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (d:\xampp-7.3.2\htdocs\newforum\themes\Bootstrap\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (d:\xampp-7.3.2\htdocs\newforum\themes\Bootstrap\gulpfile.js:54:6)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```

Cause is a breaking change in gulp version 4.0.0.
https://www.liquidlight.co.uk/blog/how-do-i-update-to-gulp-4/

Why 4.0.0? Because running `NPM Install` automatically installed the latest version. Probably best to test it before you merge.

### CODE REVIEW

**Comment by Megalomaniak** [comment]
Hmm, in fact it's probably best you recreate this fix yourself since I seem to have made a bit of a mess in the history there...

**Comment by TwistedTwigleg** [comment]
I can recreate the fix myself if you want, or I can squish the five commits into one and then merge that. Either way, I'll see about getting this into the repository after testing.

**Comment by Megalomaniak** [comment]
That just fixed the `npm run build` seems there is more to do in the file to fix `npm run watch` but I've yet to wrap my head around that. In case you are still using gulp 3.9.x you are probably best off holding off on changing this. Since migration to v4 would be a requirement to both of us at the same time.

**Comment by TwistedTwigleg** [comment]
Okay. If it is cool with you, then let's hold off for now then and once everything with the forums is more or less stable, then see about updating/migrating to v4.

**Comment by Megalomaniak** [comment]
For now I have the change already made on one of my local branches that I can use to build the theme with, and I guess I don't really outright need the watch task. So for now on my end I guess it is indeed fine.

When npm installing I did notice it listed a lot of deprecation warnings and warned also of quite a few security vulnerabilities. Not sure how serious it was/is but might deserve an open issue and maybe a closer inspection.

**Comment by TwistedTwigleg** [comment]
Sounds good. I might see about updating gulp then, so long as `npm build` still works, as I never really used `npm watch` when I've been working on the themes. I just ran `npm build` after making changes.

The warnings about deprecation are not too concerning, at least not in the short term, but the security vulnerabilities are a a bit more concerning.

I doubt we'll need to worry about them right now, as I cannot imagine too many people would be interested in breaking through the security measures of the forums, but it is definitely something to look into in the near future!

Hopefully fixing most of the security vulnerabilities will just be changing a few things here and there.

**Comment by TwistedTwigleg** [comment]
Okay, I update gulp to version 4.0.0, made the change in the build file (copy-pasted your change) and made sure building still works. I also updated the `package.json` file to require gulp version 4.0.0, since it will no longer work with older versions, and removed my notes from the readme so later we can move them to the wiki.

I also looked briefly through the security vulnerabilities list npm showed. From what I can gather, many if not all of the issues are related to packages the theme uses. Maybe we can find a way to update those packages or manually patch the vulnerabilities ourselves.

Thanks for the changes, and my apologizes on muddling up the commits! I wanted to quickly pull in these changes, since without them new users will be unable to build the them, but moving forward I'll work on a separate branch to make things easier.

Thanks again! Closing this pull request...

**Pull request closed without merging**
